### PR TITLE
fix code length, maxlength of inputs and menu (#231)(#237)(#238)

### LINKED ISSUE #231: Kod poniżej 7 znaków u studenta
długość kodu przy wchodzeniu u studenta wchodzi nawet przy kodzie poniżej 7 znaków - do poprawy
Najlepiej jakby działało jak na localhoscie. Kod podany przez Router jest akceptowany odrazu a jeśli takiego nie ma to kod jest wprowadzany ręcznie i input jest cały czas widoczny.
Czyli warunek na pojawienie się inputa to "props.session == undefined" (nie jestem pewien jak deno podaje dane)
A w przeciwnym razie props.session zapisywane jest do useState połączonego z inputem, i input nie pojawia się.

### LINKED ISSUE #237: ograniczyć długości inputów
Input nazwiska,
Input imienia
Input tytułu quizu,
Input tytułu pytania
Limity na takim poziomie żeby mieściły się w listach w których się wyświetlają.

### LINKED ISSUE #238: Zmiana nazw w menu
zmiana nazwy karty UCZESTNICY na SESJA i ROZPOCZNIJ SESJE na SESJA
zmiana STWORZ QUIZ na QUIZY

### PR DESCRIPTION
**Pull request by michal367**
fixed code length at student, closes #231
maxlength of inputs (question title, quiz title, name, surname), closes #237
changed menu texts, closes #238

### CODE REVIEW

**Review by Petros9 — APPROVED** [review]
seems alright to me

File: src/student/components/joinSessionView/StudentFormView.tsx [hunk 1]
```diff
@@ -172,7 +174,7 @@ export function StudentFormView(props: StudentFormViewProps) {
                     style={{ width: '100%', maxWidth: "350px" }}
                 />}
             </Backdrop>
-            {!session && (
+            {(!session || session.length !== 7) && (
```
Comment (Derstilon) [inline src/student/components/joinSessionView/StudentFormView.tsx]: It won't do because if you mistype the wrong digit you can't change it once the session variable hits valid length. I've made pull request for your branch that addresses this issue and fixes it #282

**Review by Derstilon — CHANGES_REQUESTED** [review]

**Review by Derstilon — APPROVED** [review]
