### PR TITLE
Fix submiting on enter

### LINKED ISSUE #136: Enter dołącza do sesji w widoku dołączania do sesji
Dodanie funkcjonalności akceptacji dołączenia do sesji po wciśnięciu Enter oraz naprawa błędu że formularz przeładowuje stronę po wciśnięciu enter.
Potencjalne rozwiązania: 
[1](https://stackoverflow.com/questions/895171/prevent-users-from-submitting-a-form-by-hitting-enter)
[2](https://stackoverflow.com/questions/33211672/how-to-submit-a-form-using-enter-key-in-react-js)
[3](https://stackoverflow.com/questions/43750335/react-prevent-form-submission-when-enter-is-pressed-inside-input/50977097)
[4](https://www.reddit.com/r/reactjs/comments/czbuet/pressing_return_key_refreshes_page/)

### PR DESCRIPTION
**Pull request by Karolk99**

### CODE REVIEW

File: src/student/components/joinSessionView/StudentFormView.tsx [hunk 1]
```diff
@@ -146,6 +146,24 @@ export function StudentFormView(props: StudentFormViewProps) {
         }
     }
 
+    useEffect(() => {
+        const listener = (event: { code: string; preventDefault: () => void; }) => {
+          if (event.code === "Enter" || event.code === "NumpadEnter") {
+            console.log("Enter key was pressed. Run your function.");
```
Comment (Derstilon) [inline src/student/components/joinSessionView/StudentFormView.tsx]: This console.log can be removed 
```suggestion
```

**Review by Derstilon — CHANGES_REQUESTED** [review]
Good job.
Delete this one console.log and you can merge those changes :)

**Review by ostatni5 — APPROVED** [review]
obraz

**Review by Derstilon — APPROVED** [review]
