### PR TITLE
Fix/student quiz checkbox

### LINKED ISSUE #311: Odświeżanie checkboxów

### PR DESCRIPTION
**Pull request by Karolk99**

### CODE REVIEW

**Review by michal367 — CHANGES_REQUESTED** [review]
obraz
There is some error when sending second quiz to student

You can add `if` in line 138 with checking if it is undefined

File: src/student/components/quizView/QuestionsList.tsx [hunk 1]
```diff
@@ -10,20 +10,48 @@ export function QuestionsList() {
...
+            values[i] = []
+            let len;
+            if(quiz.questions[i].options === undefined) continue;
+            else{  len = quiz.questions[i].options!.length;}
+            for(let j = 0; j < len; j++)
+                values[i].push(false);
+            
+        }
+        setCheckboxValues(values);
     }, []);
```
Comment (Derstilon) [inline src/student/components/quizView/QuestionsList.tsx]: You are setting new quiz data but setQuiz only schedules the change of state and it will be done in the next rerender of the component. You have to use the quiz from the payload in the loop and not quiz the state because it hasn't updated yet. Maybe change the fillCheckboxValues function to accept the quiz object on input and use that?
```suggestion
    const refreshQuiz = useCallback((payload: ServerQuizRequestPayload) => {
        console.log("refreshQuiz");
        setQuiz(payload.data.questions);
        setQuizID(payload.data.quiz_id);
        setCheckboxValues(fillcheckboxValues(payload.data)); //TODO update fillcheckboxValues implementation to accept quiz type in parameters
    }, []);
```

**Review by Derstilon — CHANGES_REQUESTED** [review]

File: src/student/components/quizView/QuestionsList.tsx [hunk 2]
```diff
@@ -10,8 +10,25 @@ export function QuestionsList() {
...
+
+    const fillcheckboxValues = () => {
+        let values : boolean[][] = [];
+        for(let i = 0; i < quiz.questions.length; i++) {
+            values[i] = []
+            let len;
+            if(quiz.questions[i].options === undefined) continue;
+            else{  len = quiz.questions[i].options!.length;}
+            for(let j = 0; j < len; j++)
+                values[i].push(false);
```
Comment (michal367) [inline src/student/components/quizView/QuestionsList.tsx]: Repetition # 1

File: src/student/components/quizView/QuestionsList.tsx [hunk 3]
```diff
@@ -24,6 +41,17 @@ export function QuestionsList() {
...
         setQuiz(payload.data.questions);
         setQuizID(payload.data.quiz_id);
+        let values : boolean[][] = [];
+        for(let i = 0; i < payload.data.questions.questions.length; i++) {
+            values[i] = []
+            let len;
+            if(payload.data.questions.questions[i].options === undefined) continue;
+            else{  len = payload.data.questions.questions[i].options!.length;}
+            for(let j = 0; j < len; j++)
+                values[i].push(false);
```
Comment (michal367) [inline src/student/components/quizView/QuestionsList.tsx]: Repetition # 2

File: src/student/components/quizView/QuestionsList.tsx [hunk 4]
```diff
@@ -77,6 +110,17 @@ export function QuestionsList() {
...
         console.log(payload);
         sendJsonMessage(payload);
+        let values : boolean[][] = [];
+        for(let i = 0; i < quiz.questions.length; i++) {
+            values[i] = []
+            let len;
+            if(quiz.questions[i].options === undefined) continue;
+            else{  len = quiz.questions[i].options!.length;}
+            for(let j = 0; j < len; j++)
+                values[i].push(false);
```
Comment (michal367) [inline src/student/components/quizView/QuestionsList.tsx]: Repetition # 3

File: src/student/components/quizView/QuestionsList.tsx [hunk 5]
```diff
@@ -10,8 +10,25 @@ export function QuestionsList() {
...
     const [quizID, setQuizID] = useState("");
+
+    const fillcheckboxValues = () => {
+        let values : boolean[][] = [];
+        for(let i = 0; i < quiz.questions.length; i++) {
+            values[i] = []
+            let len;
+            if(quiz.questions[i].options === undefined) continue;
+            else{  len = quiz.questions[i].options!.length;}
+            for(let j = 0; j < len; j++)
```
Comment (michal367) [inline src/student/components/quizView/QuestionsList.tsx]: Why this weird `len` variable instead of `j < quiz.questions[i].options!.length`?

**Review by michal367 — CHANGES_REQUESTED** [review]
Bug when I've sent quiz with more questions than previous one
obraz

**Review by Derstilon — COMMENTED** [review]
Had to do it myself

**Review by Derstilon — APPROVED** [review]

**Review by michal367 — APPROVED** [review]
