### PR TITLE
Multiple features and fixes for session and reactions

### LINKED ISSUE #181: Refactor kart Uczestnicy i Rozpocznij sesję
Zamiast dwóch kart z linkiem, jedna karta z jednym albo drugim linkiem w zależności od aktywności sesji

### LINKED ISSUE #230: Dodanie drugiego trybu reakcji po kliknięciu.
Zmienia się tryb
Ten typ reakcji nie znika wtedy po 15s nieaktywności
Da się wrócić do standardowego trybu

### PR DESCRIPTION
**Pull request by Derstilon**
Reactions will now be preserved if their state will be toggled with a click
image
Reaction animations won't overlap with each other
Code for tabs was fixed

### CODE REVIEW

**Review by michal367 — APPROVED** [review]
obraz

File: src/lecturer/components/reactionReceiveView/ReactionCounter.tsx [hunk 1]
```diff
@@ -3,40 +3,66 @@ import React, {
...
+    currentMode: boolean;
+    onMode: () => void;
 }
 
 export function ReactionCounter(props: ReactionCounterProps) {
     const [value, setValue] = useState<number>(props.value);
     const [changed, setChanged] = useState<boolean>(true);
+    const [mode, setMode] = useState<boolean>(props.currentMode);
+    
+
```
Comment (ostatni5) [inline src/lecturer/components/reactionReceiveView/ReactionCounter.tsx]: remove empty lines

**Review by ostatni5 — APPROVED** [review]
Good job

a
